### ISSUE TITLE
symdiff doesn't work for recent revisions

### ISSUE THREAD

**Issue by theCapypara** [UsernameFodder/pmdsky-debug#95]
**Describe the bug**
`tools/symdiff.py` errors on recent diffs.

**To Reproduce**
1. in `tools` run `python3 symdiff.py bf40a32..HEAD`

**Expected behavior**
I expect it to work.

**Python environment**
Python 3.10.8

```
aiodns==3.0.0
aiohttp==3.8.1
aiosignal==1.2.0
antlr4-python3-runtime==4.8
appdirs==1.4.4
argcomplete==2.0.0
astroid==2.11.5
async-timeout==4.0.2
attrs==21.4.0
black==22.3.0
Brotli==1.0.9
bsdiff4==1.2.2
cairocffi==1.3.0
CairoSVG==2.5.2
cchardet==2.1.7
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
click==8.0.3
colorama==0.4.4
crcmod==1.7
cssselect2==0.4.1
defusedxml==0.7.1
dill==0.3.5
-e git+ssh://git@github.com/SkyTemple/dungeon-eos.git@069bffe4290b6ff746e46b112059bd5c713f36ec#egg=dungeon_eos
execnet==1.9.0
-e git+ssh://git@github.com/SkyTemple/ExplorerScript.git@ca2502370eab78aba95e243225e17380b6413c9e#egg=explorerscript
frozenlist==1.3.0
gbulb==0.6.2
gitdb==4.0.9
gitdb2==4.0.2
GitPython==3.0.8
gql==3.3.0
graphql-core==3.2.1
idna==3.3
igraph==0.9.9
importlib-metadata==4.11.3
iniconfig==1.1.1
isort==5.10.1
Jinja2==3.1.2
jsonschema==4.1.2
keystone-engine==0.9.2
lazy-object-proxy==1.7.1
libcst==0.4.5
lru-dict==1.1.8
lxml==4.9.0
MarkupSafe==2.1.1
mccabe==0.7.0
mido==1.2.10
multidict==6.0.2
mypy==0.931
mypy-extensions==0.4.3
natsort==8.1.0
ndspy==3.0.0
nest-asyncio==1.5.4
ninfs==1.6.1
ordered-set==4.1.0
packaging==21.3
parameterized==0.8.1
pathspec==0.9.0
pep517==0.6.0
Pillow==9.1.1
platformdirs==2.5.2
pluggy==1.0.0
pmdsky-debug-py @ file:///home/marco/dev/skytemple/skytemple/pmdsky_debug_py/src
-e git+ssh://git@github.com/SkyTemple/pmdsky-debug-py.git@df846f7bd3aa4876a3e36d13d7b2be624baf83e4#egg=pmdsky_debug_py_generator&subdirectory=generator
psutil==5.9.0
py==1.11.0
# Editable install with no version control (py-desmume==0.0.5)
-e /home/marco/.virtualenvs/skytemple/lib/python3.10/site-packages
pycairo==1.20.1
pycares==4.1.2
pycln==1.3.5
pycparser==2.21
pycryptodomex==3.14.1
pyenchant==3.2.2
pygal==3.0.0
PyGObject==3.42.2
pygtkspellcheck==5.0.1
pylint==2.13.9
pyparsing==3.0.7
pypresence==4.2.1
pyrsistent==0.18.1
pytest==7.0.1
pytest-dotenv==0.5.2
pytest-forked==1.4.0
pytest-xdist==2.5.0
python-dateutil==2.8.2
python-dotenv==0.19.2
-e git+ssh://git@github.com/Parakoopa/python-for-android.git@42be0f74e17035f27c0c5f54232d382d73401a13#egg=python_for_android
pytoml==0.1.21
PyYAML==6.0
range-typed-integers==1.0.1
requirements-parser==0.5.0
sentry-sdk==1.5.6
sf2utils==0.9.0
sh==1.14.2
six==1.16.0
-e git+ssh://git@github.com/SkyTemple/skytemple.git@6ff7193334b5d4461707f5f6691eeef3268d5e4c#egg=skytemple
skytemple-3rdparty-typestubs==1.0.0.post2
-e git+ssh://git@github.com/SkyTemple/skytemple-dtef.git@282559b882cabd3def6e695a85af84337cae9d35#egg=skytemple_dtef
-e git+ssh://git@github.com/SkyTemple/skytemple-files.git@8615defeb2afd095364f87d942b0a7a136f1109a#egg=skytemple_files
-e git+ssh://git@github.com/SkyTemple/skytemple-icons.git@352f12fb83abf54bf5c7a4af163b50bc4931aa07#egg=skytemple_icons
-e git+ssh://git@github.com/SkyTemple/skytemple-randomizer.git@abcbcaa8a53520367106f2bab48a86638b264ca2#egg=skytemple_randomizer
skytemple-rust==1.4.0
-e git+ssh://git@github.com/SkyTemple/skytemple-ssb-debugger.git@ef9346c6fc53ffd58687df34d85ff9c066462c74#egg=skytemple_ssb_debugger
smmap==5.0.0
sortedcollections==2.1.0
sortedcontainers==2.4.0
strictyaml==1.6.1
texttable==1.6.4
# Editable install with no version control (tilequant==0.4.1)
-e /home/marco/.virtualenvs/skytemple/lib/python3.10/site-packages
tinycss2==1.1.1
toml==0.10.2
tomli==2.0.1
tornado==6.1
typer==0.4.1
types-Pillow==8.3.8
types-PyYAML==6.0.4
types-setuptools==57.4.9
types-toml==0.10.7
typing-inspect==0.7.1
typing_extensions==4.1.1
urllib3==1.26.8
webencodings==0.5.1
wrapt==1.14.1
xmldiff==2.4
xmltodict==0.13.0
yarl==1.7.2
yq==2.14.0
zipp==3.8.0
```

**Comment by theCapypara** [comment]
Replacing the syntax so that instead of `..` a space is used results in a new error:
```
Schwerwiegend: Pfad 'symbols/arm7.yml' befindet sich im Dateisystem, aber nicht in 'bf40a32'

Traceback (most recent call last):
  File "/home/marco/dev/skytemple/skytemple/pmdsky_debug_py/pmdsky-debug/tools/symdiff.py", line 1046, in <module>
    preceding_newline |= print_symbol_diff(
  File "/home/marco/dev/skytemple/skytemple/pmdsky_debug_py/pmdsky-debug/tools/symdiff.py", line 881, in print_symbol_diff
    old_table = SymbolTable(path, revision=base, descriptions=descriptions)
  File "/home/marco/dev/skytemple/skytemple/pmdsky_debug_py/pmdsky-debug/tools/symdiff.py", line 762, in __init__
    with open_file_at_revision(path, revision) as f:
  File "/home/marco/dev/skytemple/skytemple/pmdsky_debug_py/pmdsky-debug/tools/symdiff.py", line 119, in open_file_at_revision
    return StringIO(git_cmd(["show", f"{revision}:{path_from_root}"]))
  File "/home/marco/dev/skytemple/skytemple/pmdsky_debug_py/pmdsky-debug/tools/symdiff.py", line 73, in git_cmd
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', '-C', '/home/marco/dev/skytemple/skytemple/pmdsky_debug_py/pmdsky-debug', '--no-pager', 'show', 'bf40a32:symbols/arm7.yml']' returned non-zero exit status 128.
```

**Comment by theCapypara** [comment]
The issue was my system lanuage, symdiff currently only works with english git error messages.

**Comment by UsernameFodder** [comment]
> The issue was my system lanuage, symdiff currently only works with english git error messages.

This is still a valid issue TBH :P.
